name: small beer
favicon: null
layout_spectrum: 0.25802
typography_spectrum: 0.28105
title: 'smallbeer: a blog about the art & craft of homebrewing'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#B8B42D'
    - '#697A21'
    - '#FFFCE8'
    - '#3E363F'
    - '#DD403A'
  brandStrength: 0.37831400777213275
  lightness: 0.1009945331607014
  saturation: 0.8215611118357629
  rhythmicContrast: 0.54654958890751
purpose: []
